/**
 * http://usejsdoc.org/
 */
var RbDmsAPI = require('./index.js');

var opts = {
		apiUrl: 'rbdms-uat.cloudhub.io'
		};

var oauthParams = {
		host: 'rboauth2.cloudhub.io',
		port: 80,
		clientId: '89412b6a67084fee872636e487e66970',
		clientSecret: 'a547facd634f454096D9ED83CB5FA9E4'
		};

var qryParams = {
		countryCode: 'EA',
		dbName: 'TEST'
		};
	
var RbDms = new RbDmsAPI(opts);

/**
 * Get a list of Credit Notes/
 */
RbDms.get('creditNotes', oauthParams, qryParams);

/**
 * Post a list of CreditNotes/
 */
var creditNotesList = JSON.stringify([
                                      {
                                          "creditNoteNo": "SODKH68000005",
                                          "creditNoteKey": "SODKHDKH68201609131042265",
                                          "distributorCode": "DKSH",
                                          "distributorName": "DKSH",
                                          "customerCode": "CT0000000001",
                                          "customerName": "K.S. Pharmacy",
                                          "customerReferenceNo": "CT500",
                                          "salesmanCode": "B68",
                                          "salesmanName": "JOHN",
                                          "warehouseCode": "WH_DKSH",
                                          "warehouseName": "WH_DKSH",
                                          "status": "I",
                                          "creditNoteDate": "2016-09-13",
                                          "billToCode": "CT0000000001",
                                          "distributorTaxId": "37684766",
                                          "customerTaxRegistrationNo": "DKH68",
                                          "customerMunicipalNo": "CT19866",
                                          "productRelated": 1,
                                          "stockMovementIndicator": 1,
                                          "fullReversalIndicator": 1,
                                          "invoiceNo": "768586",
                                          "invoiceKey": "768586",
                                          "claimableIndicator": 1,
                                          "creditNoteType": "G",
                                          "handHeldReturnNo": "234",
                                          "customerTaxIndicator": 1,
                                          "grossTotal": 789.1324,
                                          "netTotal": 789.1324,
                                          "netTotalTaxIncluded": 789.1324,
                                          "adjustedAmount": 789.1324,
                                          "taxableAmount": 789.1324,
                                          "nonTaxableAmount": 789.1324,
                                          "taxPercentage1": 789.132,
                                          "taxPercentage2": 789.134,
                                          "taxPercentage3": 789.124,
                                          "taxTotal1": 789.1324,
                                          "taxTotal2": 789.1324,
                                          "taxTotal3": 789.1324,
                                          "taxTotal": 789.1324,
                                          "customerGroupDiscount": 789.1324,
                                          "customerDiscountPercentage": 789.324,
                                          "customerDiscountAmount": 789.1324,
                                          "totalDiscount": 789.1324,
                                          "createdDate": "2016-09-13T10:45:52Z",
                                          "createdBy": "CT68",
                                        "lineItems": [
                                          {  
                                            "productIndex": 32,
                                            "productCode": "8021405",
                                            "productDescription": "GAVIS",
                                            "sellingType": "S",
                                            "uomCode": "EA",
                                            "warehouseCodeDetail": "WH_DKSH",
                                            "warehouseNameDetail": "WH_DKSH",
                                            "defaultUomCode": "EA",
                                            "productQuantity": 5.456,
                                            "originalQuantity": 5.456,
                                            "mrp": 4.1234,
                                            "costPrice": 5.1234,
                                            "productListPrice": 100.1234,
                                            "uomListPrice": 200.1234,
                                            "grossAmount": 789.1365,
                                            "productDiscount": 789.1365,
                                            "promoDiscount": 789.1324,
                                            "salesDiscount": 789.1324,
                                            "netAmount": 789.1326,
                                            "netAmountTaxIncluded": 789.1326,
                                            "customerGroupDiscountDetail": 789.1399,
                                            "cashDiscountPercentage": 789.1324,
                                            "cashDiscountAmount": 789.1354,
                                            "customerDiscountAmountDetail": 789.1354,
                                            "taxPercentage1Detail": 789.35,
                                            "taxPercentage2Detail": 789.12,
                                            "taxPercentage3Detail": 789.34,
                                            "taxAmount1": 15.4353,
                                            "taxAmount2": 62.3463,
                                            "taxAmount3": 37.3454,
                                            "totalTaxAmount": 84.5673,
                                            "remarks": "TEST REMARK",
                                            "reasonCode": "TEST reason",
                                            "reasonDescription": "TEST RSN DESC",
                                            "invoiceNoDetail": "768586",
                                            "invoiceKeyDetail": "768586",
                                            "parentProduct": "KGH",
                                            "parentUom": "CA",
                                            "taxCode": "2"
                                          },
                                          {  
                                            "productIndex": 33,
                                            "productCode": "8021405",
                                            "productDescription": "GAVIS",
                                            "sellingType": "S",
                                            "uomCode": "EA",
                                            "warehouseCodeDetail": "WH_DKSH",
                                            "warehouseNameDetail": "WH_DKSH",
                                            "defaultUomCode": "EA",
                                            "productQuantity": 5.456,
                                            "originalQuantity": 5.456,
                                            "mrp": 4.1234,
                                            "costPrice": 5.1234,
                                            "productListPrice": 100.1234,
                                            "uomListPrice": 200.1234,
                                            "grossAmount": 789.1365,
                                            "productDiscount": 789.1365,
                                            "promoDiscount": 789.1324,
                                            "salesDiscount": 789.1324,
                                            "netAmount": 789.1326,
                                            "netAmountTaxIncluded": 789.1326,
                                            "customerGroupDiscountDetail": 789.1399,
                                            "cashDiscountPercentage": 789.1324,
                                            "cashDiscountAmount": 789.1354,
                                            "customerDiscountAmountDetail": 789.1354,
                                            "taxPercentage1Detail": 789.35,
                                            "taxPercentage2Detail": 789.12,
                                            "taxPercentage3Detail": 789.34,
                                            "taxAmount1": 15.4353,
                                            "taxAmount2": 62.3463,
                                            "taxAmount3": 37.3454,
                                            "totalTaxAmount": 84.5673,
                                            "remarks": "TEST REMARK",
                                            "reasonCode": "TEST reason",
                                            "reasonDescription": "TEST RSN DESC",
                                            "invoiceNoDetail": "768586",
                                            "invoiceKeyDetail": "768586",
                                            "parentProduct": "KGH",
                                            "parentUom": "CA",
                                            "taxCode": "2"
                                          }
                                        ]
                                      },
                                      {
                                          "creditNoteNo": "SODKH68000006",
                                          "creditNoteKey": "SODKHDKH68201609131042266",
                                          "distributorCode": "DKSH",
                                          "distributorName": "DKSH",
                                          "customerCode": "CT0000000001",
                                          "customerName": "K.S. Pharmacy",
                                          "customerReferenceNo": "CT500",
                                          "salesmanCode": "B68",
                                          "salesmanName": "JOHN",
                                          "warehouseCode": "WH_DKSH",
                                          "warehouseName": "WH_DKSH",
                                          "status": "I",
                                          "creditNoteDate": "2016-09-13",
                                          "billToCode": "CT0000000001",
                                          "distributorTaxId": "37684766",
                                          "customerTaxRegistrationNo": "DKH68",
                                          "customerMunicipalNo": "CT19866",
                                          "productRelated": 1,
                                          "stockMovementIndicator": 1,
                                          "fullReversalIndicator": 1,
                                          "invoiceNo": "768586",
                                          "invoiceKey": "768586",
                                          "claimableIndicator": 1,
                                          "creditNoteType": "G",
                                          "handHeldReturnNo": "234",
                                          "customerTaxIndicator": 1,
                                          "grossTotal": 789.1324,
                                          "netTotal": 789.1324,
                                          "netTotalTaxIncluded": 789.1324,
                                          "adjustedAmount": 789.1324,
                                          "taxableAmount": 789.1324,
                                          "nonTaxableAmount": 789.1324,
                                          "taxPercentage1": 789.132,
                                          "taxPercentage2": 789.134,
                                          "taxPercentage3": 789.124,
                                          "taxTotal1": 789.1324,
                                          "taxTotal2": 789.1324,
                                          "taxTotal3": 789.1324,
                                          "taxTotal": 789.1324,
                                          "customerGroupDiscount": 789.1324,
                                          "customerDiscountPercentage": 789.324,
                                          "customerDiscountAmount": 789.1324,
                                          "totalDiscount": 789.1324,
                                          "createdDate": "2016-09-13T10:45:52Z",
                                          "createdBy": "CT68",
                                        "lineItems": [
                                          {  
                                            "productIndex": 34,
                                            "productCode": "8021405",
                                            "productDescription": "GAVIS",
                                            "sellingType": "S",
                                            "uomCode": "EA",
                                            "warehouseCodeDetail": "WH_DKSH",
                                            "warehouseNameDetail": "WH_DKSH",
                                            "defaultUomCode": "EA",
                                            "productQuantity": 5.456,
                                            "originalQuantity": 5.456,
                                            "mrp": 4.1234,
                                            "costPrice": 5.1234,
                                            "productListPrice": 100.1234,
                                            "uomListPrice": 200.1234,
                                            "grossAmount": 789.1365,
                                            "productDiscount": 789.1365,
                                            "promoDiscount": 789.1324,
                                            "salesDiscount": 789.1324,
                                            "netAmount": 789.1326,
                                            "netAmountTaxIncluded": 789.1326,
                                            "customerGroupDiscountDetail": 789.1399,
                                            "cashDiscountPercentage": 789.1324,
                                            "cashDiscountAmount": 789.1354,
                                            "customerDiscountAmountDetail": 789.1354,
                                            "taxPercentage1Detail": 789.35,
                                            "taxPercentage2Detail": 789.12,
                                            "taxPercentage3Detail": 789.34,
                                            "taxAmount1": 15.4353,
                                            "taxAmount2": 62.3463,
                                            "taxAmount3": 37.3454,
                                            "totalTaxAmount": 84.5673,
                                            "remarks": "TEST REMARK",
                                            "reasonCode": "TEST reason",
                                            "reasonDescription": "TEST RSN DESC",
                                            "invoiceNoDetail": "768586",
                                            "invoiceKeyDetail": "768586",
                                            "parentProduct": "KGH",
                                            "parentUom": "CA",
                                            "taxCode": "2"
                                          },
                                          {  
                                            "productIndex": 35,
                                            "productCode": "8021405",
                                            "productDescription": "GAVIS",
                                            "sellingType": "S",
                                            "uomCode": "EA",
                                            "warehouseCodeDetail": "WH_DKSH",
                                            "warehouseNameDetail": "WH_DKSH",
                                            "defaultUomCode": "EA",
                                            "productQuantity": 5.456,
                                            "originalQuantity": 5.456,
                                            "mrp": 4.1234,
                                            "costPrice": 5.1234,
                                            "productListPrice": 100.1234,
                                            "uomListPrice": 200.1234,
                                            "grossAmount": 789.1365,
                                            "productDiscount": 789.1365,
                                            "promoDiscount": 789.1324,
                                            "salesDiscount": 789.1324,
                                            "netAmount": 789.1326,
                                            "netAmountTaxIncluded": 789.1326,
                                            "customerGroupDiscountDetail": 789.1399,
                                            "cashDiscountPercentage": 789.1324,
                                            "cashDiscountAmount": 789.1354,
                                            "customerDiscountAmountDetail": 789.1354,
                                            "taxPercentage1Detail": 789.35,
                                            "taxPercentage2Detail": 789.12,
                                            "taxPercentage3Detail": 789.34,
                                            "taxAmount1": 15.4353,
                                            "taxAmount2": 62.3463,
                                            "taxAmount3": 37.3454,
                                            "totalTaxAmount": 84.5673,
                                            "remarks": "TEST REMARK",
                                            "reasonCode": "TEST reason",
                                            "reasonDescription": "TEST RSN DESC",
                                            "invoiceNoDetail": "768586",
                                            "invoiceKeyDetail": "768586",
                                            "parentProduct": "KGH",
                                            "parentUom": "CA",
                                            "taxCode": "2"
                                          }
                                        ]
                                      }
                                    ]);

RbDms.post('creditNotes', creditNotesList, oauthParams, qryParams);


