/**
 * http://usejsdoc.org/
 */
var RbDmsAPI = require('./index.js');

var opts = {
		apiUrl: 'rbdms-uat.cloudhub.io'
		};

var oauthParams = {
		host: 'rboauth2.cloudhub.io',
		port: 80,
		clientId: '89412b6a67084fee872636e487e66970',
		clientSecret: 'a547facd634f454096D9ED83CB5FA9E4'
		};

var qryParams = {
		countryCode: 'EA',
		dbName: 'TEST'
		};
	
var RbDms = new RbDmsAPI(opts);

/**
 * Get a list of Invoices/
 */
RbDms.get('invoices', oauthParams, qryParams);

/**
 * Post a list of Invoices/
 */
var invoicesList = JSON.stringify([
                                   {
                                	      "invoiceNo": "5322083575",
                                	      "invoiceKey": "5322083575",
                                	      "distributorCode": "339825",
                                	      "distributorName": "DKSH",
                                	      "customerCode": "170014557",
                                	      "customerName": "JOHN",
                                	      "customerReferenceNo": "170014557",
                                	      "customerType": "Q",
                                	      "customerTaxRegNo": "RBB67",
                                	      "salesmanCode": "12345",
                                	      "salesmanName": "MATHEW",
                                	      "orderNo": "SODKTRBB67000005",
                                	      "orderKey": "SODKTDKTRBB67201610041950425",
                                	      "purchaseOrderNo": "SODKTRBB67000005",
                                	      "warehouseCode": "OTC_WHS",
                                	      "warehouseDescription": "OTC_WHS",
                                	      "billToCode": "170014557",
                                	      "shipToCode": "170014557",
                                	      "invoiceStatus": "S",
                                	      "invoiceDate": "2016-10-04",
                                	      "invoiceDueDate": "2016-10-04",
                                	      "orderDate": "2016-10-04",
                                	      "deliveryDate": "2016-10-04",
                                	      "taxInvoiceNo": "AB1234",
                                	      "pickListIndicator": 1,
                                	      "invoiceIndicator": "C",
                                	      "referenceNo": "ABC5678",
                                	      "grossTotal": 789.1324,
                                	      "netTotal": 789.1324,
                                	      "netTotalTax": 789.1324,
                                	      "adjustedAmount": 789.1324,
                                	      "taxableAmount": 789.1324,
                                	      "taxableFocAmount": 879.1245,
                                	      "nonTaxableAmount": 789.1324,
                                	      "taxPercentage1": 789.132,
                                	      "taxPercentage2": 789.134,
                                	      "taxPercentage3": 789.124,
                                	      "taxTotal1": 789.1324,
                                	      "taxTotal2": 789.1324,
                                	      "taxTotal3": 789.1324,
                                	      "taxTotal": 789.1324,
                                	      "customerDiscountPercentage": 789.324,
                                	      "customerDiscountAmount": 789.1324,
                                	      "productDiscountTotal": 789.1324,
                                	      "claimDiscount": 789.1324,
                                	      "distributorDiscount": 897.4586,
                                	      "promoDiscount": 789.1324,
                                	      "salesDiscount": 789.1324,
                                	      "cashDiscount": 789.1324,
                                	      "customerGroupDiscount": 789.1324,
                                	      "remark": "TEST REMARK",
                                	      "createdDateTime": "2016-09-13T10:45:52Z",
                                	      "createdBy": "DKH68",
                                	      "visitKey": "VSDKHDKH68201609131042254",
                                	      "lineItems": [
                                	      {
                                		      "productIndex": 30,
                                		      "productCode": "8021405",
                                		      "productDescription": "GAVIS",
                                		      "uomCode": "TH",
                                		      "taxIndicator": 1,
                                		      "sellingType": "S",
                                		      "defaultUomCode": "12X24X10ML",
                                		      "productQuantity": 5.456,
                                		      "mrp": 4.1234,
                                		      "costPrice": 5.1234,
                                		      "productListPrice": 100.1234,
                                		      "uomListPrice": 200.1234,
                                		      "grossAmount": 789.1365,
                                		      "productDiscount": 789.1365,
                                		      "promoDiscountDetail": 789.1348,
                                		      "distributorPromotionDiscount": 987.1298,
                                		      "hqPromotionDiscount": 688.9987,
                                		      "salesDiscountDetail": 789.1348,
                                		      "customerGroupDiscountDetail": 789.1399,
                                		      "cashDiscountPercentage": 45.879,
                                		      "cashDiscountDetail": 66.6754,
                                		      "netAmount": 789.1326,
                                		      "netAmountTax": 789.1326,
                                		      "netAmountOfFocItem": 789.1326,
                                		      "customerDiscount": 789.1354,
                                		      "taxPercentage1Detail": 789.35,
                                		      "taxPercentage2Detail": 789.12,
                                		      "taxPercentage3Detail": 789.34,
                                		      "taxAmount1": 15.4353,
                                		      "taxAmount2": 62.3463,
                                		      "taxAmount3": 37.3454,
                                		      "taxAmount": 84.5673,
                                		      "conversionFactorToSmallestUom": 5.123,
                                		      "taxCode": "2",
                                		      "parentProduct": "SDF975",
                                		      "parentUom": "CA",
                                		      "promo": {
                                		      	  "promoCode": "distributorDKH01",
                                			      "promoIndex": 15,
                                			      "promoSequence": 2335,
                                			      "mechanicType": "3",
                                			      "discountPercentage": 5.343,
                                			      "discountAmount": 10.4578,
                                			      "discountSpentAmount": 2.4563,
                                			      "claimIndicator": 1,
                                			      "claimableIndicator": 1,
                                			      "budgetAmount": 45.8797,
                                			      "invoiceProductIndex": 25
                                			   }
                                		    },
                                		    {
                                		      "productIndex": 31,
                                		      "productCode": "8021405",
                                		      "productDescription": "GAVIS",
                                		      "uomCode": "TH",
                                		      "taxIndicator": 1,
                                		      "sellingType": "S",
                                		      "defaultUomCode": "12X24X10ML",
                                		      "productQuantity": 5.456,
                                		      "mrp": 4.1234,
                                		      "costPrice": 5.1234,
                                		      "productListPrice": 100.1234,
                                		      "uomListPrice": 200.1234,
                                		      "grossAmount": 789.1365,
                                		      "productDiscount": 789.1365,
                                		      "promoDiscountDetail": 789.1348,
                                		      "distributorPromotionDiscount": 987.1298,
                                		      "hqPromotionDiscount": 688.9987,
                                		      "salesDiscountDetail": 789.1348,
                                		      "customerGroupDiscountDetail": 789.1399,
                                		      "cashDiscountPercentage": 45.879,
                                		      "cashDiscountDetail": 66.6754,
                                		      "netAmount": 789.1326,
                                		      "netAmountTax": 789.1326,
                                		      "netAmountOfFocItem": 789.1326,
                                		      "customerDiscount": 789.1354,
                                		      "taxPercentage1Detail": 789.35,
                                		      "taxPercentage2Detail": 789.12,
                                		      "taxPercentage3Detail": 789.34,
                                		      "taxAmount1": 15.4353,
                                		      "taxAmount2": 62.3463,
                                		      "taxAmount3": 37.3454,
                                		      "taxAmount": 84.5673,
                                		      "conversionFactorToSmallestUom": 5.123,
                                		      "taxCode": "2",
                                		      "parentProduct": "SDF975",
                                		      "parentUom": "CA",
                                		      "promo": {
                                			      "promoCode": "distributorDKH01",
                                			      "promoIndex": 15,
                                			      "promoSequence": 2335,
                                			      "mechanicType": "3",
                                			      "discountPercentage": 5.343,
                                			      "discountAmount": 10.4578,
                                			      "discountSpentAmount": 2.4563,
                                			      "claimIndicator": 1,
                                			      "claimableIndicator": 1,
                                			      "budgetAmount": 45.8797,
                                			      "invoiceProductIndex": 25
                                		      }
                                		    }
                                		 ]
                                	  },
                                	  {
                                	      "invoiceNo": "5322083576",
                                	      "invoiceKey": "5322083576",
                                	      "distributorCode": "339825",
                                	      "distributorName": "DKSH",
                                	      "customerCode": "170014557",
                                	      "customerName": "JOHN",
                                	      "customerReferenceNo": "170014557",
                                	      "customerType": "Q",
                                	      "customerTaxRegNo": "RBB67",
                                	      "salesmanCode": "12345",
                                	      "salesmanName": "MATHEW",
                                	      "orderNo": "SODKTRBB67000005",
                                	      "orderKey": "SODKTDKTRBB67201610041950425",
                                	      "purchaseOrderNo": "SODKTRBB67000005",
                                	      "warehouseCode": "OTC_WHS",
                                	      "warehouseDescription": "OTC_WHS",
                                	      "billToCode": "170014557",
                                	      "shipToCode": "170014557",
                                	      "invoiceStatus": "S",
                                	      "invoiceDate": "2016-10-04",
                                	      "invoiceDueDate": "2016-10-04",
                                	      "orderDate": "2016-10-04",
                                	      "deliveryDate": "2016-10-04",
                                	      "taxInvoiceNo": "AB1234",
                                	      "pickListIndicator": 1,
                                	      "invoiceIndicator": "C",
                                	      "referenceNo": "ABC5678",
                                	      "grossTotal": 789.1324,
                                	      "netTotal": 789.1324,
                                	      "netTotalTax": 789.1324,
                                	      "adjustedAmount": 789.1324,
                                	      "taxableAmount": 789.1324,
                                	      "taxableFocAmount": 879.1245,
                                	      "nonTaxableAmount": 789.1324,
                                	      "taxPercentage1": 789.132,
                                	      "taxPercentage2": 789.134,
                                	      "taxPercentage3": 789.124,
                                	      "taxTotal1": 789.1324,
                                	      "taxTotal2": 789.1324,
                                	      "taxTotal3": 789.1324,
                                	      "taxTotal": 789.1324,
                                	      "customerDiscountPercentage": 789.324,
                                	      "customerDiscountAmount": 789.1324,
                                	      "productDiscountTotal": 789.1324,
                                	      "claimDiscount": 789.1324,
                                	      "distributorDiscount": 897.4586,
                                	      "promoDiscount": 789.1324,
                                	      "salesDiscount": 789.1324,
                                	      "cashDiscount": 789.1324,
                                	      "customerGroupDiscount": 789.1324,
                                	      "remark": "TEST REMARK",
                                	      "createdDateTime": "2016-09-13T10:45:52Z",
                                	      "createdBy": "DKH68",
                                	      "visitKey": "VSDKHDKH68201609131042254",
                                	    "lineItems": [
                                	    {
                                		      "productIndex": 32,
                                		      "productCode": "8021405",
                                		      "productDescription": "GAVIS",
                                		      "uomCode": "TH",
                                		      "taxIndicator": 1,
                                		      "sellingType": "S",
                                		      "defaultUomCode": "12X24X10ML",
                                		      "productQuantity": 5.456,
                                		      "mrp": 4.1234,
                                		      "costPrice": 5.1234,
                                		      "productListPrice": 100.1234,
                                		      "uomListPrice": 200.1234,
                                		      "grossAmount": 789.1365,
                                		      "productDiscount": 789.1365,
                                		      "promoDiscountDetail": 789.1348,
                                		      "distributorPromotionDiscount": 987.1298,
                                		      "hqPromotionDiscount": 688.9987,
                                		      "salesDiscountDetail": 789.1348,
                                		      "customerGroupDiscountDetail": 789.1399,
                                		      "cashDiscountPercentage": 45.879,
                                		      "cashDiscountDetail": 66.6754,
                                		      "netAmount": 789.1326,
                                		      "netAmountTax": 789.1326,
                                		      "netAmountOfFocItem": 789.1326,
                                		      "customerDiscount": 789.1354,
                                		      "taxPercentage1Detail": 789.35,
                                		      "taxPercentage2Detail": 789.12,
                                		      "taxPercentage3Detail": 789.34,
                                		      "taxAmount1": 15.4353,
                                		      "taxAmount2": 62.3463,
                                		      "taxAmount3": 37.3454,
                                		      "taxAmount": 84.5673,
                                		      "conversionFactorToSmallestUom": 5.123,
                                		      "taxCode": "2",
                                		      "parentProduct": "SDF975",
                                		      "parentUom": "CA",
                                		      "promo": {
                                			      "promoCode": "distributorDKH01",
                                			      "promoIndex": 15,
                                			      "promoSequence": 2335,
                                			      "mechanicType": "3",
                                			      "discountPercentage": 5.343,
                                			      "discountAmount": 10.4578,
                                			      "discountSpentAmount": 2.4563,
                                			      "claimIndicator": 1,
                                			      "claimableIndicator": 1,
                                			      "budgetAmount": 45.8797,
                                			      "invoiceProductIndex": 25
                                		      }
                                		    },
                                		    {
                                		      "productIndex": 33,
                                		      "productCode": "8021405",
                                		      "productDescription": "GAVIS",
                                		      "uomCode": "TH",
                                		      "taxIndicator": 1,
                                		      "sellingType": "S",
                                		      "defaultUomCode": "12X24X10ML",
                                		      "productQuantity": 5.456,
                                		      "mrp": 4.1234,
                                		      "costPrice": 5.1234,
                                		      "productListPrice": 100.1234,
                                		      "uomListPrice": 200.1234,
                                		      "grossAmount": 789.1365,
                                		      "productDiscount": 789.1365,
                                		      "promoDiscountDetail": 789.1348,
                                		      "distributorPromotionDiscount": 987.1298,
                                		      "hqPromotionDiscount": 688.9987,
                                		      "salesDiscountDetail": 789.1348,
                                		      "customerGroupDiscountDetail": 789.1399,
                                		      "cashDiscountPercentage": 45.879,
                                		      "cashDiscountDetail": 66.6754,
                                		      "netAmount": 789.1326,
                                		      "netAmountTax": 789.1326,
                                		      "netAmountOfFocItem": 789.1326,
                                		      "customerDiscount": 789.1354,
                                		      "taxPercentage1Detail": 789.35,
                                		      "taxPercentage2Detail": 789.12,
                                		      "taxPercentage3Detail": 789.34,
                                		      "taxAmount1": 15.4353,
                                		      "taxAmount2": 62.3463,
                                		      "taxAmount3": 37.3454,
                                		      "taxAmount": 84.5673,
                                		      "conversionFactorToSmallestUom": 5.123,
                                		      "taxCode": "2",
                                		      "parentProduct": "SDF975",
                                		      "parentUom": "CA",
                                		      "promo": {
                                			      "promoCode": "distributorDKH01",
                                			      "promoIndex": 15,
                                			      "promoSequence": 2335,
                                			      "mechanicType": "3",
                                			      "discountPercentage": 5.343,
                                			      "discountAmount": 10.4578,
                                			      "discountSpentAmount": 2.4563,
                                			      "claimIndicator": 1,
                                			      "claimableIndicator": 1,
                                			      "budgetAmount": 45.8797,
                                			      "invoiceProductIndex": 25
                                		      }
                                		    }
                                		 ]
                                	  }
                                	]);

RbDms.post('invoices', invoicesList, oauthParams, qryParams);

